scraping_django_3/accounts/urls.py
from django.urls import path
from accounts.views import (login_view,logout_view,
register_view,update_view, delete_view, contact)


app_name = 'accounts'

urlpatterns = [
    path('login/',login_view,name='login'),
    path('logout/',logout_view,name='logout'),
    path('register/',register_view,name='register'),
    path('update/',update_view,name='update'),
    path('delete/', delete_view, name='delete'),
    path('contact/', contact, name='contact'),
]

scraping_django_3/templates/base.html
{% load static %}
{% url 'accounts:update' as update_url %}
{% url 'accounts:register' as register_url %}
{% url 'accounts:login' as login_url %}
{% url 'home' as home_url %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="icon" href="{% static 'favicon.ico' %}">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <title>{% block title %}Amazing Blog{% endblock %}</title>
  </head>
  <body>
    <div class="container">
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'home' %}" id="brand">JobFind</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item {% if request.path == home_url %} active {% endif %}">
              <a class="nav-link" href="{% url 'home' %}">Home<span class="sr-only">(current)</span></a>
            </li>
            {% if user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:logout' %}">Выйти</a>
              </li>
              <li class="nav-item {% if request.path == update_url %} active {% endif %}">
                <a class="nav-link" href="{% url 'accounts:update' %}">Профиль</a>
              </li>
              {% else %}
              <li class="nav-item {% if request.path == login_url %} active {% endif %}">
                <a class="nav-link" href="{% url 'accounts:login' %}">Войти</a>
              </li>
              <li class="nav-item {% if request.path == register_url %} active {% endif %}">
                <a class="nav-link" href="{% url 'accounts:register' %}">Зарегистрироваться</a>
              </li>
            {% endif %}
          </ul>
        </div>
      </nav>
    </div>
    <div class="container">
      <div class="row">
        <div class="col-8 mx-auto my-3">
          {% if messages %}
              {% for message in messages %}
                  {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                      <div class="alert alert-danger alert-dismissible fade show" role="alert">
                        {{ message }} 
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                        </button>
                      </div>
                  {% else %}
                      <div class="alert alert-success alert-dismissible fade show" role="alert">
                        {{ message }} 
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                        </button>
                      </div>
                  {% endif %}
              {% endfor %}
          {% endif %}
        </div>
      </div>
    </div>
    <div class="container">
      {% block content %}



      {% endblock %}
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  </body>
</html>