scraping_django_3/accounts/urls.py
from django.urls import path
from accounts.views import (login_view,logout_view,
register_view,update_view, delete_view, contact)


app_name = 'accounts'

urlpatterns = [
    path('login/',login_view,name='login'),
    path('logout/',logout_view,name='logout'),
    path('register/',register_view,name='register'),
    path('update/',update_view,name='update'),
    path('delete/', delete_view, name='delete'),
    path('contact/', contact, name='contact'),
]

scraping_django_3/accounts/models.py
from django.db import models
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser


class MyUserManager(BaseUserManager):
    def create_user(self, email, password=None):
        """
        Creates and saves a User with the given email, date of
        birth and password.
        """
        if not email:
            raise ValueError('Users must have an email address')

        user = self.model(
            email=self.normalize_email(email),

        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None):
        """
        Creates and saves a superuser with the given email, date of
        birth and password.
        """
        user = self.create_user(
            email,
            password=password,
        )
        user.is_admin = True
        user.save(using=self._db)
        return user


class MyUser(AbstractBaseUser):
    email = models.EmailField(
        verbose_name='email address',
        max_length=255,
        unique=True,
    )
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    city = models.ForeignKey('scraping.City', on_delete=models.SET_NULL,
    null=True,blank=True)
    language = models.ForeignKey('scraping.Language', on_delete=models.SET_NULL,
    null=True,blank=True)
    send_email = models.BooleanField(default=True)
    objects = MyUserManager()

    USERNAME_FIELD = 'email'

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True

    @property
    def is_staff(self):
        "Is the user a member of staff?"
        # Simplest possible answer: All admins are staff
        return self.is_admin

scraping_django_3/accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model,authenticate
from django.contrib.auth.hashers import check_password
from scraping.models import City,Language
User = get_user_model()
class UserLoginForm(forms.Form):
    email = forms.CharField(widget=forms.EmailInput(attrs={'class':'form-control'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control'}))

    def clean(self, *args, **kwargs):
        email = self.cleaned_data.get('email').strip()
        password = self.cleaned_data.get('password').strip()

        if email and password:
            qs = User.objects.filter(email=email)
            if not qs.exists():
                raise forms.ValidationError('Такого пользователя нет')
            if not check_password(password,qs[0].password):
                raise forms.ValidationError('Пароль не верный!')
            user = authenticate(email=email,password=password)
            if not user:
                raise forms.ValidationError('Данный аккаунт отключен')
        return super(UserLoginForm, self).clean(*args,**kwargs)

class UserRegistrationForm(forms.ModelForm):
    email = forms.CharField(label='Введите email',
    widget=forms.EmailInput(attrs={'class':'form-control'}))
    password = forms.CharField(label='Введите пароль',
    widget=forms.PasswordInput(attrs={'class':'form-control'}))
    password2 = forms.CharField(label='Введите пароль ещё раз',
    widget=forms.PasswordInput(attrs={'class':'form-control'}))
    class Meta:
        model = User
        fields = ('email',)

    def clean_password2(self):
        data = self.cleaned_data
        if data['password'] != data['password2']:
            raise forms.ValidationError('Пароли не совпадают')
        return data['password2']

class UserUpdateForm(forms.Form):

    city = forms.ModelChoiceField(queryset=City.objects.all(), to_field_name='slug', 
    required=True, widget=forms.Select(attrs={'class':'form-control'}), label='Город')

    language = forms.ModelChoiceField(queryset=Language.objects.all(), to_field_name='slug',
    required=True, widget=forms.Select(attrs={'class':'form-control'}), label='Специальность')

    send_email = forms.BooleanField(required=False, widget=forms.CheckboxInput,label='Получать рассылку?')

    class Meta:
        model = User
        fields = ('city','language','send_email')

class ContactForm(forms.Form):
    city = forms.CharField(required=True, widget=forms.TextInput(attrs={'class':'form-control'}), label='Город')

    language = forms.CharField(required=True, widget=forms.TextInput(attrs={'class':'form-control'}), label='Специальность')
    
    email = forms.CharField(label='Введите email',required=True, widget=forms.EmailInput(attrs={'class':'form-control'}))

scraping_django_3/accounts/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import authenticate,login,logout,get_user_model
from .forms import UserLoginForm,UserRegistrationForm,UserUpdateForm,ContactForm
from django.contrib.auth.base_user import AbstractBaseUser
from django.contrib import messages 
from scraping.models import Error
import datetime as dt

User = get_user_model()

def login_view(request):
    form = UserLoginForm(request.POST or None)
    if form.is_valid():
        data = form.cleaned_data
        email = data.get('email')
        password = data.get('password')
        user = authenticate(request, email=email, password=password)
        login(request, user)
        return redirect('home')
    return render(request, 'accounts/login.html',{'form':form})

def logout_view(request):
    logout(request)
    return redirect('home')


def register_view(request):
    form = UserRegistrationForm(request.POST or None)
    if form.is_valid():
        new_user = form.save(commit=False)
        new_user.set_password(form.cleaned_data['password'])
        new_user.save()
        messages.success(request, 'Вы успешно зарегистрированы')
        return render(request, 'accounts/register_done.html',{'new_user':new_user})
    return render(request, 'accounts/register.html',{'form':form})

def update_view(request):
    contact_form = ContactForm()
    if request.user.is_authenticated:
        user = request.user
        if request.method == 'POST':
            form = UserUpdateForm(request.POST)
            if form.is_valid():
                data = form.cleaned_data
                user.city = data['city']
                user.language = data['language']
                user.send_email = data['send_email']
                user.save()
                messages.success(request, 'Данные сохранены.')
                return redirect('accounts:update')

        form = UserUpdateForm(initial={'city': user.city, 
        'language': user.language, 'send_email':user.send_email})
        return render(request, 'accounts/update.html',
        {'form':form, 'contact_form':contact_form})
    else:
        return redirect('accounts:login')

def delete_view(request):
    if request.user.is_authenticated:
        user = request.user
        if request.method == 'POST':
            qs = User.objects.get(pk=user.pk)
            qs.delete()
            messages.error(request, 'Пользователь удалён :(')

    return redirect('home')

def contact(request):
    if request.method == 'POST':
        contact_form = ContactForm(request.POST or None)
        if contact_form.is_valid():
            data = contact_form.cleaned_data
            city = data.get('city')
            language = data.get('language')
            email = data.get('email')
            qs = Error.objects.filter(timestamp=dt.date.today())
            if qs.exists:
                err = qs.first()
                data = err.data.get('user_data',[])
                data.append({'city': city,'language':language,'email':email})
                err.data['user_data'] = data
                err.save()
            else:
                data = [{'city': city,'language':language,'email':email}]
                Error(data=f"user_data:{data}").save()
            messages.success(request,'Данные отправлены администрации')
            return redirect('accounts:update')
        else:
            return redirect('accounts:update')
    else:
        return redirect('accounts:login')

scraping_django_3/accounts/templates/accounts/login.html
{% extends 'base.html' %}


{% block title %}
    Login
{% endblock title %}
    

{% block content %}

<div class="row">
  <div class="col-md-8 mx-auto">
    <h4 class="my-2">Форма входа</h4>
    <form method="POST" action="">
        {% csrf_token %}
      <div class="form-group">
        {{ form.as_p }}
      </div>
      <button type="submit" class="btn btn-primary">Войти</button>
    </form>
  </div>
</div>

{% endblock %}

scraping_django_3/accounts/templates/accounts/register.html
{% extends 'base.html' %}


{% block title %}
    Registration
{% endblock title %}
    

{% block content %}

<div class="row">
  <div class="col-md-8 mx-auto">
    <h4 class="my-2">Регистрация нового пользователя</h4>
    <form method="POST" action="">
        {% csrf_token %}
      <div class="form-group">
        {{ form.as_p }}
      </div>
      <button type="submit" class="btn btn-primary">Зарегистрироваться</button>
    </form>
  </div>
</div>

{% endblock %}

scraping_django_3/accounts/templates/accounts/register_done.html
{% extends 'base.html' %}


{% block title %}
    Registration
{% endblock title %}
    

{% block content %}

<div class="row">
  <div class="col-md-8 mx-auto">
    <h4 class="my-2">Приветствуем нового пользователя {{ new_user.email }}</h4>
    <p>Вы зарегистрировались в системе. Теперь вы можете <a href="{% url 'accounts:login' %}">войти.</a>    </p>
  </div>
</div>

{% endblock %}

scraping_django_3/accounts/templates/accounts/update.html
{% extends 'base.html' %}


{% block title %}
    Registration
{% endblock title %}
    

{% block content %}

<div class="row">
  <div class="col-md-8 mx-auto">
    <h4 class="my-2">Настройки</h4>
    <form method="POST" action="">
        {% csrf_token %}
      <div class="form-group">
        {{ form.as_p }}
      </div>
      <button type="submit" class="btn btn-primary">Сохранить</button>
    </form>
    <form method="POST" action="{% url 'accounts:delete' %}">
        {% csrf_token %}
      <button type="submit" class="btn btn-danger my-3">Удалить</button>
      <p>
        <h6>Если вашей вакансии нет, вы можете её предложить добавить администратору</h6>
        <button class="btn btn-success" type="button" data-toggle="collapse" data-target="#collapsed" aria-expanded="false" aria-controls="collapseExample">
          Показать форму 
        </button>
      </p>
      
      <div class="collapse" id="collapsed">
        <div class="card card-body">
          <div class="row my-5">
            <div class="col-md-8 mx-auto">

              <h6 class="my-2">Если вы не нашли подходящий набор Город, Специальность, 
                Вы можете заполнить форму ниже с Вашими пожеланиями. После того,
                как необходимые данные будут добавлены, Вы получите письмо на указанный Вам email
              </h6>
              <form method="POST" action="{% url 'accounts:contact' %}">
                  {% csrf_token %}
                <div class="form-group">
                  {{ contact_form.as_p }}
                </div>
                <button type="submit" class="btn btn-primary">Отправить</button>
              </form>
            </div>
          </div>
        </div>
      </div>
    </form>
  </div>
</div>
{% endblock %}